// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[code].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/_app.tsx";
import * as $4 from "./routes/_middleware.ts";
import * as $5 from "./routes/admin/_middleware.ts";
import * as $6 from "./routes/admin/clean-db.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/oauth.tsx";
import * as $9 from "./routes/privacy.tsx";
import * as $10 from "./routes/profile/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/DeleteShortCode.tsx";

const manifest = {
  routes: {
    "./routes/[code].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/_app.tsx": $3,
    "./routes/_middleware.ts": $4,
    "./routes/admin/_middleware.ts": $5,
    "./routes/admin/clean-db.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/oauth.tsx": $8,
    "./routes/privacy.tsx": $9,
    "./routes/profile/index.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/DeleteShortCode.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
